### PR TITLE
Utm using geographiclib foxy

### PR DESCRIPTION
**Pull request by Timple**
Parallel to #626

### CODE REVIEW

**Comment by SteveMacenski** [comment]
I leave this to @ayrton04 too since I really don't know much about this. If it compiles / dependencies are properly marked in package.xml/cmakelists, I see no issue with it

**Comment by SteveMacenski** [comment]
https://build.ros2.org/job/Fpr__robot_localization__ubuntu_focal_amd64/31/gcc/

CI failed due to an unused variable warning

**Comment by Timple** [comment]
The unused variable is there for backwards/abi compatibility. Shall I mark it as ignored?

**Comment by SteveMacenski** [comment]
Which?

**Comment by Timple** [comment]
The compiler warning was correct. `gamma` is actually a function-output, so it should have been set. 
This was correct in the noetic implementation, got lost in migration I guess. Fixed now.

**Review by ayrton04 — APPROVED** [review]

**Pull request merged**
