### PR TITLE
Fixing minor uncrustify failures.

### PR DESCRIPTION
**Pull request by JWhitleyWork**
Running `colcon test --packages-select robot_localization` on the `dashing-devel` branch currently fails with a few minor `uncrustify` errors. This fixes those errors.

### CODE REVIEW

**Review by SteveMacenski — APPROVED** [review]

**Comment by SteveMacenski** [comment]
f

**Comment by SteveMacenski** [comment]
@mabelzhang can you pull that into your eloquent PR?

**Comment by maximus5684** [comment]
@SteveMacenski - I'm going to make another using all of the linting tools (the major ones missing are `flake8` and `ament_copyright`).

**Comment by JWhitleyWork** [comment]
Oops. Wrong account.

**Comment by mabelzhang** [comment]
Yes. I found a parameter "expected double got int" error when launching navsat_transform.launch.py, so I need to fix that in `dashing-devel` first before making the eloquent PR :X Looking into that today

**Pull request merged**
