### PR TITLE
Fixing lat-long to UTM conversion

### PR DESCRIPTION
**Pull request by ayrton04**
Addresses https://github.com/cra-ros-pkg/robot_localization/issues/619.

FYI @kosmastsk

### CODE REVIEW

**Comment by ayrton04** [comment]
@kosmastsk, would you be able/willing to test this?

**Comment by kosmastsk** [comment]
@ayrton04 I will test it soon and let you know if the issue is fixed.

**Comment by SteveMacenski** [comment]
@kosmastsk please submit for ROS2 as well

**Comment by ayrton04** [comment]
I'll take care of porting it once we've confirmed it works.

**Comment by kosmastsk** [comment]
@ayrton04 I just checked it with the same data that I used when I made the issue, and now it works fine! Thank you!
Do you want me to file an issue for nav2 as well?

**Review by SteveMacenski — APPROVED** [review]
No issues if you say it works! I'm not working with GPS right now to be able to independently verify but the code looks good (obviously...)

**Pull request merged**
