### PR TITLE
Add broadcast_utm_transform_as_parent_frame description to doc

### PR DESCRIPTION
**Pull request by diasdm**
Regarding issue #445 
* Added the parameter description
* Fixed what I believe was a typo in the Published Transforms description

### CODE REVIEW

**Comment by Timple** [comment]
So if I use `broadcast_utm_transform_as_parent_frame` do I also still need `broadcast_utm_transform`?
Haven't looked at the code, just following documentation :)

**Comment by diasdm** [comment]
[I believe so](https://github.com/cra-ros-pkg/robot_localization/blob/f6bf556407945e7b192c78959c51d2f10f62e488/src/navsat_transform.cpp#L288), if you want the transform to be published at all, you have to set ``broadcast_utm_transform`` to true.

**Comment by Timple** [comment]
My point was that this was not clear from the documentation :). So this might be added.
(Thanks for looking it up though)

**Comment by diasdm** [comment]
What is your suggestion? To change what is stated [here](https://github.com/cra-ros-pkg/robot_localization/pull/446/files#diff-67c66a3bfd4085a496b7ce4d7abbc936R53), to something else?
To `Note that for the transform to be published ``broadcast_utm_transform`` also has to be set to *true*.`, for example?

**Comment by ayrton04** [comment]
I think both should be required, and I think the additional note is a good idea.

Thanks very much for doing this!

**Review by ayrton04 — APPROVED** [review]

**Pull request merged**
