### PR TITLE
Fix warnings when building against Rolling.

### PR DESCRIPTION
**Pull request by clalancette**
Rolling has moved header files (deprecating the old one), and changed the preferred form of some templated classes (like TimeSynchronizer).  Fix those warnings here.

Note that this should *only* be applied for Rolling, as it will fail to compile for earlier versions of ROS 2.

### CODE REVIEW

**Review by SteveMacenski — APPROVED** [review]

**Comment by SteveMacenski** [comment]
@ayrton04 is this test known to be flaky? I don't believe I've seen this failure before 

```
06:34:49 33: [test_ekf_node_interfaces-2] [ RUN      ] InterfacesTest.ImuDifferentialIO
06:34:49 33: [test_ekf_node_interfaces-2] /tmp/ws/src/robot_localization/test/test_se_node_interfaces.cpp:830: Failure
06:35:01 33: [test_ekf_node_interfaces-2] Expected: (std::abs(rollFinal)) < (0.2), actual: 1.2032755481031931 vs 0.2
06:35:01 33: [test_ekf_node_interfaces-2] 
06:35:01 33: [test_ekf_node_interfaces-2] /tmp/ws/src/robot_localization/test/test_se_node_interfaces.cpp:831: Failure
06:35:01 33: [test_ekf_node_interfaces-2] Expected: (std::abs(pitchFinal)) < (0.2), actual: 0.65010049931252023 vs 0.2
06:35:01 33: [test_ekf_node_interfaces-2] 
06:35:01 33: [test_ekf_node_interfaces-2] /tmp/ws/src/robot_localization/test/test_se_node_interfaces.cpp:832: Failure
06:35:01 33: [test_ekf_node_interfaces-2] Expected: (std::abs(yawFinal)) < (0.2), actual: 2.2377817033514558 vs 0.2
06:35:01 33: [test_ekf_node_interfaces-2] 
06:35:01 33: [ekf_node-1] [INFO] [1724420101.340558210] [test_se_node_interfaces]: Received a request to reset filter.
06:35:01 33: [test_ekf_node_interfaces-2] [  FAILED  ] InterfacesTest.ImuDifferentialIO (12004 ms)
```

**Comment by ayrton04** [comment]
Whoops, please disregard this comment. I see this is rolling only.

**Review by ayrton04 — APPROVED** [review]

**Comment by clalancette** [comment]
> Whoops, please disregard this comment. I see this is rolling only.

Yes, exactly.  I will point out that after this merge, it is no longer possible to release `robot_localization` into Humble, Iron, or Jazzy.  I might suggest making a branch prior to this commit to support those, but that is up to you.

**Comment by clalancette** [comment]
> Yes, exactly. I will point out that after this merge, it is no longer possible to release `robot_localization` into Humble, Iron, or Jazzy. I might suggest making a branch prior to this commit to support those, but that is up to you.

Ah, never mind this.  There are already branches for other distributions, so we should be set here.  Thanks!

**Pull request merged**
