### PR TITLE
Added subscription to stamped topic

### PR DESCRIPTION
**Pull request by pvela2017**
Addresses Issue #822 not subscribing to twist stamped topics.

### CODE REVIEW

**Review by ayrton04 — APPROVED** [review]
LGTM! I'll wait for the build to pass before merging.

**Comment by pvela2017** [comment]
Whops, it seems to be some problems with the format, sorry about that. I didn't know.

I guess I should change the else to this, isn't it?
` } else {`
  
Is there something else I should change?

**Comment by ayrton04** [comment]
If you want to test locally, you can run `colcon test --packages-select robot_localization --event-handlers=console_direct+"`

**Comment by pvela2017** [comment]
Hi, thank you for the advice, after fixing the error I tested locally and all the tests were ok. 
But now there is a different error in the build:
`[ukf_node-1] [ERROR] [1725529437.477895556] [test_se_node_interfaces]: Failed to meet update rate! Took 8.7472036880000008097seconds. Try decreasing the rate, limiting sensor output frequency, or limiting the number of sensors.`

Screenshot from 2024-09-05 17-23-41

**Comment by ayrton04** [comment]
That's not an error. It's just a warning that indicates the computer running the tests is too slow.

**Comment by ayrton04** [comment]
Kicking the build farm again. That should not cause the test to fail.

**Comment by ayrton04** [comment]
```
10:39:20 35: [test_ukf_node_interfaces-2] [ RUN      ] InterfacesTest.OdomTwistBasicIO
10:39:20 35: [ukf_node-1] [INFO] [1725529180.322946848] [test_se_node_interfaces]: Received a request to reset filter.
10:39:40 35: [ukf_node-1] [INFO] [1725529200.320729109] [test_se_node_interfaces]: Received a request to reset filter.
10:40:00 35: [ukf_node-1] [INFO] [1725529220.326575588] [test_se_node_interfaces]: Received a request to reset filter.
10:40:20 35: [ukf_node-1] [ERROR] [1725529221.605134503] [test_se_node_interfaces]: Failed to meet update rate! Took 0.10496924400000000321seconds. Try decreasing the rate, limiting sensor output frequency, or limiting the number of sensors.
10:42:50 35: [ukf_node-1] [ERROR] [1725529368.932831886] [test_se_node_interfaces]: Failed to meet update rate! Took 7.0019397359999997477seconds. Try decreasing the rate, limiting sensor output frequency, or limiting the number of sensors.
10:43:02 35: [ukf_node-1] [ERROR] [1725529377.730226063] [test_se_node_interfaces]: Failed to meet update rate! Took 1.8481952479999999017seconds. Try decreasing the rate, limiting sensor output frequency, or limiting the number of sensors.
10:43:07 35: [ukf_node-1] [ERROR] [1725529382.740402755] [test_se_node_interfaces]: Failed to meet update rate! Took 1.0368385810000000369seconds. Try decreasing the rate, limiting sensor output frequency, or limiting the number of sensors.
10:43:16 35: [ukf_node-1] [ERROR] [1725529392.185660324] [test_se_node_interfaces]: Failed to meet update rate! Took 2.971192713999999846seconds. Try decreasing the rate, limiting sensor output frequency, or limiting the number of sensors.
10:43:35 35: [ukf_node-1] [ERROR] [1725529402.187806208] [test_se_node_interfaces]: Failed to meet update rate! Took 1.600955970000000006seconds. Try decreasing the rate, limiting sensor output frequency, or limiting the number of sensors.
10:43:50 35: [ukf_node-1] [ERROR] [1725529420.132188720] [test_se_node_interfaces]: Failed to meet update rate! Took 4.331398809000000405seconds. Try decreasing the rate, limiting sensor output frequency, or limiting the number of sensors.
10:44:07 35: [ukf_node-1] [ERROR] [1725529437.477895556] [test_se_node_interfaces]: Failed to meet update rate! Took 8.7472036880000008097seconds. Try decreasing the rate, limiting sensor output frequency, or limiting the number of sensors.
10:44:27 35/42 Test #35: test_ukf_node_interfaces ..........................***Timeout 309.63 sec
10:44:27 test 36
10:44:27       Start 36: test_robot_localization_estimator
```

The test just timed out. We haven't touched that test in a long time. My guess is a transient build farm issue.

**Comment by pvela2017** [comment]
> ```
> 10:39:20 35: [test_ukf_node_interfaces-2] [ RUN      ] InterfacesTest.OdomTwistBasicIO
> 10:39:20 35: [ukf_node-1] [INFO] [1725529180.322946848] [test_se_node_interfaces]: Received a request to reset filter.
> 10:39:40 35: [ukf_node-1] [INFO] [1725529200.320729109] [test_se_node_interfaces]: Received a request to reset filter.
> 10:40:00 35: [ukf_node-1] [INFO] [1725529220.326575588] [test_se_node_interfaces]: Received a request to reset filter.
> 10:40:20 35: [ukf_node-1] [ERROR] [1725529221.605134503] [test_se_node_interfaces]: Failed to meet update rate! Took 0.10496924400000000321seconds. Try decreasing the rate, limiting sensor output frequency, or limiting the number of sensors.
> 10:42:50 35: [ukf_node-1] [ERROR] [1725529368.932831886] [test_se_node_interfaces]: Failed to meet update rate! Took 7.0019397359999997477seconds. Try decreasing the rate, limiting sensor output frequency, or limiting the number of sensors.
> 10:43:02 35: [ukf_node-1] [ERROR] [1725529377.730226063] [test_se_node_interfaces]: Failed to meet update rate! Took 1.8481952479999999017seconds. Try decreasing the rate, limiting sensor output frequency, or limiting the number of sensors.
> 10:43:07 35: [ukf_node-1] [ERROR] [1725529382.740402755] [test_se_node_interfaces]: Failed to meet update rate! Took 1.0368385810000000369seconds. Try decreasing the rate, limiting sensor output frequency, or limiting the number of sensors.
> 10:43:16 35: [ukf_node-1] [ERROR] [1725529392.185660324] [test_se_node_interfaces]: Failed to meet update rate! Took 2.971192713999999846seconds. Try decreasing the rate, limiting sensor output frequency, or limiting the number of sensors.
> 10:43:35 35: [ukf_node-1] [ERROR] [1725529402.187806208] [test_se_node_interfaces]: Failed to meet update rate! Took 1.600955970000000006seconds. Try decreasing the rate, limiting sensor output frequency, or limiting the number of sensors.
> 10:43:50 35: [ukf_node-1] [ERROR] [1725529420.132188720] [test_se_node_interfaces]: Failed to meet update rate! Took 4.331398809000000405seconds. Try decreasing the rate, limiting sensor output frequency, or limiting the number of sensors.
> 10:44:07 35: [ukf_node-1] [ERROR] [1725529437.477895556] [test_se_node_interfaces]: Failed to meet update rate! Took 8.7472036880000008097seconds. Try decreasing the rate, limiting sensor output frequency, or limiting the number of sensors.
> 10:44:27 35/42 Test #35: test_ukf_node_interfaces ..........................***Timeout 309.63 sec
> 10:44:27 test 36
> 10:44:27       Start 36: test_robot_localization_estimator
> ```
> 
> The test just timed out. We haven't touched that test in a long time. My guess is a transient build farm issue.

Thank you! Everything seems to be ok now

**Comment by ayrton04** [comment]
Thank you!

**Comment by pvela2017** [comment]
Hello, is it possible to backport it to Humble?

**Comment by ayrton04** [comment]
Would you mind generating another PR?

**Comment by Timple** [comment]
In that case, Jazzy support would also be nice :slightly_smiling_face:

**Comment by pvela2017** [comment]
> Would you mind generating another PR?

Sure, I can do that

> In that case, Jazzy support would also be nice 🙂

ok!

**Comment by pvela2017** [comment]
Hello, 
I cherry-picked the commit  to my local jazzy and humble branches, is this the right way?
Should I create a PR using these ones [humble  ](https://github.com/pvela2017/robot_localization/commit/08344250903fd1c32ea0479644ec4c95e54d460f)  & [jazzy](https://github.com/pvela2017/robot_localization/commit/df8c9fd6f7efc715484ea0f69826b78b48645106)?

**Comment by ayrton04** [comment]
Yes please! Thank you.

**Pull request merged**
