### PR TITLE
navsat_transform diagram to address #550

### PR DESCRIPTION
**Pull request by mabelzhang**
I finally read and understood everything in #550 and created a diagram with all the points taken.

Modifications from the original diagram in #550 (other than formatting):
- `local_odometry` edge should not go from local EKF to global EKF, as Tim Clephas mentioned in the issue ticket
- Instead, global EKF takes IMU and wheel odometry as input, just like the local EKF. This makes the two EKFs have the exact same workflow, the only difference being that the global EKF exchanges information with `navsat_transform`. This is consistent with Swift Nav's diagram too.
- Changed local EKF's output `local_odometry` to `/odometry/filtered/local`, and global EKF's output to `/odometry/filtered/global`, to be uniform and clear. Also to align with EKF node's default output name.

I added the source TeX file I used to generate the image, in case people need to modify it in the future. I don't know if anybody wants that in here. Let me know if I should throw it out.

I stuck the image in the Integrating with GPS tutorial. Seems the right place.

@clalancette

### CODE REVIEW

**Comment by ayrton04** [comment]
I haven't forgotten about this. I have a major deadline this week, but will review it early next week. Thanks!

**Comment by mabelzhang** [comment]
Thank you Tom. I had waited long enough myself to make the PR that waiting for the review is fair :)

**Review by ayrton04 — APPROVED** [review]
The new diagram looks great! I think this will save considerable time for people trying to understand the setup. Thanks again for this!

**Comment by ayrton04** [comment]
@SteveMacenski, if you agree, then feel free to merge.

**Pull request merged**
