### PR TITLE
Including an end-to-end tutorial

### PR DESCRIPTION
**Pull request by methylDragon**
I wrote an end-to-end tutorial (with a video example and example implementation with ultrasonic beacons) for robot_localization, as I noticed that there hasn't been a comprehensive enough one yet.

I am hoping for this to be included somehow to help other people in the community (it was a struggle to learn how to use the package initially), doesn't have to be in this repo. Any suggestions on where I could do this would be useful (though I'd prefer not having to reformat everything to put it on the wiki..)

CH3EERS!

### CODE REVIEW

**Comment by ayrton04** [comment]
Thanks for the PR. I think a better way to do this would be to add a "user-provider tutorials" section to the regular wiki, and add a link to your tutorial.

**Comment by methylDragon** [comment]
Alrighty!

**Comment by ayrton04** [comment]
Please submit a PR to add a page of user-generated tutorials to the wiki documentation here:

https://github.com/cra-ros-pkg/robot_localization/tree/melodic-devel/doc

That way, it shows up with the [rest of the wiki on docs.ros.org](http://docs.ros.org/melodic/api/robot_localization/html/index.html).

**Comment by methylDragon** [comment]
Understood.

Is there support for Markdown, or do I need to rewrite it in .rst?

EDIT: Scratch that, I misunderstood.

**Comment by ayrton04** [comment]
Yeah, just make a new .rst file with links to user tutorials, and add yours.

P.S. - Thanks!

**Pull request closed without merging**
