### PR TITLE
Service call to pin the datum

### PR DESCRIPTION
**Pull request by kshehata**
Added a service call to pin the datum at the current localization and GPS location, and a NavSatFix publisher for the origin of the world frame.

### CODE REVIEW

**Comment by kshehata** [comment]
Paging @servos @p6chen @ablakey

**Comment by ayrton04** [comment]
Awesome, thanks for this! I'll look over it this weekend.

**Comment by kshehata** [comment]
Doh! Just noticed that I made the PR to your repo @ayrton04 and not the Clearpath fork. That said, you're welcome to these changes if you're interested in them. I was going to test them in our hydro-devel branch first.

**Comment by ayrton04** [comment]
I'll wait until you test everything and would be interested in a PR afterwards! 

Have you all added the datum setting logic to the hydro-devel branch?

**Comment by kshehata** [comment]
Not yet. We'll likely merge it to our hydro-devel in our fork for testing soon.

**Pull request closed without merging**
