### PR TITLE
Dynamic process noise

### PR DESCRIPTION
**Pull request by ayrton04**
This addresses #260. I waffled a bit on the best way to implement this, but as I'm assuming the most popular reason for wanting this change is to stop the state covariance growth on pose variables when stationary, I went with a simplified approach. I'd welcome feedback from anyone.

FYI @falkoschindler @tappan-at-git @matthewbwhitaker @servos

### CODE REVIEW

**Comment by tappan-at-git** [comment]
:+1: I like it.

**Comment by falkoschindler** [comment]
Hi Tom, it's great to hear that you tackled #260. Unfortunately, I won't be able to try it out in very near future. But I'm very much looking forward to pull and make use of these changes after completing some other subprojects, which are currently in progress.

**Comment by ayrton04** [comment]
No worries! Just tagged you in the event you wanted to weigh in.

**Comment by ayrton04** [comment]
I'll probably merge this later this week, unless I hear otherwise. The new parameter defaults to false, so it won't change the behavior.

**Comment by ayrton04** [comment]
Merging. Feel free to comment further here if there are any more opinions, and we can make changes later.

**Pull request merged**
